name: build

on:
  push:
    branches:
      - "main"

env:
  DOCKERHUB_USERNAME: lyzhang1999
  REGION_ID: 'ap-southeast-3'
  REGISTRY: swr.ap-southeast-3.myhuaweicloud.com

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          #username: ${{ env.DOCKERHUB_USERNAME }}
          #password: ${{ secrets.DOCKERHUB_TOKEN }}
          registry: swr.ap-southeast-3.myhuaweicloud.com 
          username: ${{ secrets.HUAWEI_SGP_REGISTRY_USERNAME }}
          password: ${{ secrets.HUAWEI_SGP_REGISTRY_PASSWORD }}
      - name: Build backend and push
        uses: docker/build-push-action@v5
        with:
          context: backend
          push: true
          platforms: linux/amd64,linux/arm64
          #tags: ${{ env.DOCKERHUB_USERNAME }}/:${{ steps.vars.outputs.sha_short }}
          tags: ${{ env.REGISTRY }}/${{ env.SWR_ORGANIZATION }}/backend:${{ steps.vars.outputs.sha_short }}
      - name: Build frontend and push
        uses: docker/build-push-action@v5
        with:
          context: frontend
          push: true
          platforms: linux/amd64,linux/arm64
          #tags: ${{ env.DOCKERHUB_USERNAME }}/frontend:${{ steps.vars.outputs.sha_short }}
          tags: ${{ env.REGISTRY }}/${{ env.SWR_ORGANIZATION }}/frontend:${{ steps.vars.outputs.sha_short }}
      # - name: Update helm values.yaml
      #   uses: fjogeleit/yaml-update-action@main
      #   with:
      #     valueFile: 'helm/values.yaml'
      #     commitChange: true
      #     branch: main
      #     message: 'Update Image Version to ${{ steps.vars.outputs.sha_short }}'
      #     changes: |
      #       {
      #         "backend.tag": "${{ steps.vars.outputs.sha_short }}",
      #         "frontend.tag": "${{ steps.vars.outputs.sha_short }}"
      #       }
 